### ISSUE TITLE
[Feature] Login UI

### ISSUE THREAD

**Issue by hickorysb** [hickorysb/tokovoip-dispatch-client#1]
- [x] User ID Box
- [x] Password Box
- [x] Login Box

**Comment by GameHostDirect** [comment]
What is the login details?

**Comment by hickorysb** [comment]
@GameHostDirect This project has been discontinued. This version of this software is not stable and is incomplete. Unfortunately, my server no longer uses TokoVOIP so I no longer saw a reason to continue working on this.
